prepare-requirements:
	@echo "Installing project's python requirements..."
	python -m pip install -r requirements/requirements-setup.txt
	python -m pip install -r requirements/requirements-dev.txt
	python -m pip install -r requirements/requirements-test.txt

